import React from "react";
import { Metadata } from 'next';
import {
	Roboto,
	Roboto_Condensed
} from 'next/font/google';
import { LayoutChildren } from "@/app/LayoutChildren";
import styles from "./layout.module.css";
import 'react-indiana-drag-scroll/dist/style.css';
import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const roboto = Roboto({
	subsets: ['latin'],
	variable: "--font-roboto",
	weight: ['400', '500']
});

const robotoCondensed = Roboto_Condensed({
	subsets: ['latin'],
	variable: "--font-roboto-condensed",
	weight: ["400", "700"]
});

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<head>
				<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />

				<title>Gerente de Escala</title>
			</head>

			<body
				className={`${roboto.variable} ${robotoCondensed.variable}`}
				style={{
					backgroundColor: "#111412"
				}}
			>
				<LayoutChildren>
					<div className={styles['page-container']}>
						{children}
					</div>
				</LayoutChildren>
			</body>
		</html>
	);
};